#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekz
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sr")]
	public partial class DataClasses4DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void Insertcontract(contract instance);
    partial void Updatecontract(contract instance);
    partial void Deletecontract(contract instance);
    #endregion
		
		public DataClasses4DataContext() : 
				base(global::Ekz.Properties.Settings.Default.srConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<contract> contract
		{
			get
			{
				return this.GetTable<contract>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.contract")]
	public partial class contract : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_contr;
		
		private System.Nullable<System.DateTime> _datazakl;
		
		private System.Nullable<int> _id_kl;
		
		private System.Nullable<int> _id_user;
		
		private System.Nullable<int> _id_izd;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_contrChanging(int value);
    partial void Onid_contrChanged();
    partial void OndatazaklChanging(System.Nullable<System.DateTime> value);
    partial void OndatazaklChanged();
    partial void Onid_klChanging(System.Nullable<int> value);
    partial void Onid_klChanged();
    partial void Onid_userChanging(System.Nullable<int> value);
    partial void Onid_userChanged();
    partial void Onid_izdChanging(System.Nullable<int> value);
    partial void Onid_izdChanged();
    #endregion
		
		public contract()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_contr", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_contr
		{
			get
			{
				return this._id_contr;
			}
			set
			{
				if ((this._id_contr != value))
				{
					this.Onid_contrChanging(value);
					this.SendPropertyChanging();
					this._id_contr = value;
					this.SendPropertyChanged("id_contr");
					this.Onid_contrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datazakl", DbType="Date")]
		public System.Nullable<System.DateTime> datazakl
		{
			get
			{
				return this._datazakl;
			}
			set
			{
				if ((this._datazakl != value))
				{
					this.OndatazaklChanging(value);
					this.SendPropertyChanging();
					this._datazakl = value;
					this.SendPropertyChanged("datazakl");
					this.OndatazaklChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_kl", DbType="Int")]
		public System.Nullable<int> id_kl
		{
			get
			{
				return this._id_kl;
			}
			set
			{
				if ((this._id_kl != value))
				{
					this.Onid_klChanging(value);
					this.SendPropertyChanging();
					this._id_kl = value;
					this.SendPropertyChanged("id_kl");
					this.Onid_klChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_user", DbType="Int")]
		public System.Nullable<int> id_user
		{
			get
			{
				return this._id_user;
			}
			set
			{
				if ((this._id_user != value))
				{
					this.Onid_userChanging(value);
					this.SendPropertyChanging();
					this._id_user = value;
					this.SendPropertyChanged("id_user");
					this.Onid_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_izd", DbType="Int")]
		public System.Nullable<int> id_izd
		{
			get
			{
				return this._id_izd;
			}
			set
			{
				if ((this._id_izd != value))
				{
					this.Onid_izdChanging(value);
					this.SendPropertyChanging();
					this._id_izd = value;
					this.SendPropertyChanged("id_izd");
					this.Onid_izdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
