<?xml version="1.0" encoding="utf-8"?><Database Name="sr" Class="DataClasses3DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DNS\SQLEXPRESS;Initial Catalog=sr;Integrated Security=True" SettingsObjectName="Ekz.Properties.Settings" SettingsPropertyName="srConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.izdanie" Member="izdanie">
    <Type Name="izdanie">
      <Column Name="id_izd" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_izd" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="id_user" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>